#!/bin/sh

cd ~/Projects/randux/project
pwd
npm run build

# put everything under dist
cd dist

mkdir -p static
mv bundle* static/
mv libs* static/
mv styles* static/

mkdir images
cp -r ../images/ ./images/

# create critical css version
../node_modules/.bin/critical index.html --base . --inlineImages --inline > index-critical.html
rm index.html
mv index-critical.html index.html

cp ../server/serve* .

# move icons
mkdir static/assets
mv assets/images static/assets/images
rmdir assets
