#!/bin/sh

cd ~/Projects/randux/project
pwd
npm run build

# put everything under dist
cd dist

mkdir static
mv bundle.* static/

mkdir images
cp -r ../images/ ./images/

# create critical css version
../node_modules/.bin/critical ../index.html --base . --inline > index.html

cp ../server/serve* .

# move icons
mkdir static/assets
mv assets/images static/assets/images
rmdir assets
